# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 安静看海
subtitle: ''
description: 学无止境
keywords:
author:  Peterzhu
language: zh-CN
timezone: Asia/Hangzhou

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/hardlyluckily/hardlyluckily.github.io.git
  branch: main

inject:
  head:
    - <link rel="stylesheet" href="/css/custom/index.css"  media="defer" onload="this.media='all'">
    - <script src="https://www.jq22.com/jquery/jquery-3.3.1.js"></script>
    - <script data-pjax src="https://ali-oss.xmwpro.com/cdn/js/echarts.min.js"></script>
  bottom:
    - <script src="/js/cherry.js" async></script>
menu:
  网站|| cyan-shouji:
    博客统计: /echarts/ ||  peter-zhu
footer:
  owner:
    enable: true
    since: 2022
  custom_text: <img src="" data-lazy-src="" alt="Cyan Blog 营业中" style="margin-top:10px" data-ll-status="loaded" class="entered loaded"><p style="margin:10px 0 5px"><a target="_blank" rel="noopener" href="https://hexo.io/" style="margin-inline:5px"><img src="https://ali-oss.xmwpro.com/global/hexo.svg" data-lazy-src="https://ali-oss.xmwpro.com/global/hexo.svg" alt="博客框架 Hexo" data-ll-status="loaded" class="entered loaded"></a><a target="_blank" rel="noopener" href="https://butterfly.js.org/" style="margin-inline:5px"><img src="https://ali-oss.xmwpro.com/global/Butterfly.svg" data-lazy-src="https://ali-oss.xmwpro.com/global/Butterfly.svg" alt="主题 Butterfly" data-ll-status="loaded" class="entered loaded"></a><a target="_blank" rel="noopener" href="https://github.com/" style="margin-inline:5px"><img src="https://ali-oss.xmwpro.com/global/github.svg" data-lazy-src="https://ali-oss.xmwpro.com/global/github.svg" alt="本站托管于 Github" data-ll-status="loaded" class="entered loaded"></a><a target="_blank" rel="noopener" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" style="margin-inline:5px"><img src="https://ali-oss.xmwpro.com/global/copyright.svg" data-lazy-src="https://ali-oss.xmwpro.com/global/copyright.svg" alt="本站采用知识共享署名-非商业性使用-相同方式共享4.0国际许可协议进行许可" data-ll-status="loaded" class="entered loaded"></a></p><a target="_blank" rel="noopener" href="https://beian.miit.gov.cn"><img src="/img/icp.png" data-lazy-src="/img/icp.png" alt="备案号：粤ICP备2021126986号-1" style="vertical-align:text-top;margin-right:5px" data-ll-status="loaded" class="entered loaded">备案号：粤ICP备2021126986号-1</a>
  copyright: true # Copyright of theme and framework